version: '2.4'

services:
  api:
    build:
      context: .
      target: dev
    ports:
      - 4000:3000
      - 9001:9001
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=nestjs
    restart: always
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: nestjs
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
